/* build.js: joins src/*.js into the single main.js Obsidian loads. Plain Node, no dependencies.
 *   node build.js            -> main.js
 *   node build.js --vault <path to a vault>   also copies the plugin into <vault>/.obsidian/plugins/truebrain-public */
'use strict';
const fs = require('fs'), path = require('path');
const ORDER = ['core', 'packs', 'proposals', 'plugin'];
const manifest = JSON.parse(fs.readFileSync(path.join(__dirname, 'manifest.json'), 'utf8'));
let out = "'use strict';\n/* TrueBrain Public " + manifest.version + ": generated by build.js from src/; edit the sources, not this file. */\n" +
  'const __mods = {}, __cache = {};\n' +
  "function __req(name) { if (name === 'obsidian') return require('obsidian'); const k = name.startsWith('./') ? name.slice(2) : name; " +
  'if (__cache[k]) return __cache[k].exports; const m = { exports: {} }; __cache[k] = m; __mods[k](m, m.exports, __req); return m.exports; }\n';
for (const name of ORDER) {
  const src = fs.readFileSync(path.join(__dirname, 'src', name + '.js'), 'utf8').replace(/^'use strict';\n/, '');
  out += '\n// ======== src/' + name + '.js\n__mods[' + JSON.stringify(name) + '] = function (module, exports, require) {\n' + src + '\n};\n';
}
out += "\nmodule.exports = __req('./plugin');\n";
fs.writeFileSync(path.join(__dirname, 'main.js'), out);
console.log('main.js written (' + Math.round(out.length / 1024) + ' KB)');
const vi = process.argv.indexOf('--vault');
if (vi > 0) {
  const dest = path.join(process.argv[vi + 1], '.obsidian', 'plugins', manifest.id);
  fs.mkdirSync(dest, { recursive: true });
  for (const f of ['main.js', 'manifest.json', 'styles.css']) fs.copyFileSync(path.join(__dirname, f), path.join(dest, f));
  console.log('copied to ' + dest);
}
