/* build.js: joins src/*.js into the single main.js Obsidian loads. Plain Node, no dependencies.
 *   node build.js            -> main.js
 *   node build.js --check    -> exit 1 if main.js is not exactly what the sources build (CI uses this)
 *   node build.js --vault <path to a vault>   also copies the plugin into <vault>/.obsidian/plugins/truebrain-public
 *
 * The output is the same on every machine: sources are read with any line endings and joined with LF,
 * so a Windows checkout cannot change what ships. */
'use strict';
const fs = require('fs'), path = require('path');
const ORDER = ['core', 'packs', 'proposals', 'plugin'];
const lf = (s) => s.replace(/\r\n?/g, '\n');

function bundle() {
  const manifest = JSON.parse(fs.readFileSync(path.join(__dirname, 'manifest.json'), 'utf8'));
  let out = "'use strict';\n/* TrueBrain Public " + manifest.version + ": generated by build.js from src/; edit the sources, not this file. */\n" +
    'const __mods = {}, __cache = {};\n' +
    "function __req(name) { if (name === 'obsidian') return require('obsidian'); const k = name.startsWith('./') ? name.slice(2) : name; " +
    'if (__cache[k]) return __cache[k].exports; const m = { exports: {} }; __cache[k] = m; __mods[k](m, m.exports, __req); return m.exports; }\n';
  for (const name of ORDER) {
    const src = lf(fs.readFileSync(path.join(__dirname, 'src', name + '.js'), 'utf8')).replace(/^'use strict';\n/, '');
    out += '\n// ======== src/' + name + '.js\n__mods[' + JSON.stringify(name) + '] = function (module, exports, require) {\n' + src + '\n};\n';
  }
  out += "\nmodule.exports = __req('./plugin');\n";
  return { out, manifest };
}

if (require.main === module) {
  const { out, manifest } = bundle();
  const target = path.join(__dirname, 'main.js');
  if (process.argv.includes('--check')) {
    const have = fs.existsSync(target) ? lf(fs.readFileSync(target, 'utf8')) : '';
    if (have !== out) { console.log('main.js is out of date: run node build.js and commit it'); process.exit(1); }
    console.log('main.js matches the sources'); process.exit(0);
  }
  fs.writeFileSync(target, out);
  console.log('main.js written (' + Math.round(out.length / 1024) + ' KB)');
  const vi = process.argv.indexOf('--vault');
  if (vi > 0) {
    const dest = path.join(process.argv[vi + 1], '.obsidian', 'plugins', manifest.id);
    fs.mkdirSync(dest, { recursive: true });
    for (const f of ['main.js', 'manifest.json', 'styles.css']) fs.copyFileSync(path.join(__dirname, f), path.join(dest, f));
    console.log('copied to ' + dest);
  }
}

module.exports = { bundle };
